name: icon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - fvcore
  - iopath
  - nvidiacub
  - pyembree
  - pip:
    - torch==1.12.0+cu113
    - torchvision==0.13.0+cu113